FROM python:3.9

WORKDIR /app
VOLUME /app

COPY . /app
RUN chmod +wr  /app/static
RUN pip install -r ./requirements.txt


ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]
